server:
  port: 8090

resilience4j:
  circuitbreaker:
    instances:
      circuitApiMethod: # ??? ??? ????? ??
        base-config: default # ??
    configs:
      default:
        ## sliding-window
        sliding-window-type: count_based
        sliding-window-size: 10

        ## fail
        failure-rate-threshold: 10  # open ??? ???? ?? ?? ???
        minimum-number-of-calls: 5  # ?? ??? ?? ?? ?? ?

        ## delay
        slow-call-rate-threshold: 10          # ?? ??? ?? ?? (?? ? / ???? ??? ??)
        slow-call-duration-threshold: 3000ms  # ???? ??? ??

        ## half-open
        permitted-number-of-calls-in-half-open-state: 10 # half-open?? ?? ??? ???? ?? ?? call ?
        max-wait-duration-in-half-open-state: 0 # half-open ?? ?? ?? (0? ?? ? ??? ?? ?? ? ?? ??)
        wait-duration-in-open-state: 600000ms # open ???? half-open ?? ???? ???? ??
        automatic-transition-from-open-to-half-open-enabled: true # open ???? half-open?? ?? ??(true? ?? ??? ?? ? ?? ??)
        register-health-indicator: true # ?? ?? ?? (actuator)

        ## exception ??
        record-exceptions: # ?? ??? ??? ????? ??? ???? ??? ???? ?? ?
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException